export const UI = {
  dropZone: document.getElementById('drop-zone'),
  fileInput: document.getElementById('file-input'),
  imagesDeck: document.getElementById('images-deck'),
  deckCountVal: document.getElementById('deck-count-val'),
  deckList: document.getElementById('deck-list'),
  btnClearDeck: document.getElementById('btn-clear-deck'),

  maskType: document.getElementById('mask-type'),
  layerCount: document.getElementById('layer-count'),
  layerCountVal: document.getElementById('layer-count-val'),
  maskFeather: document.getElementById('mask-feather'),
  maskFeatherVal: document.getElementById('mask-feather-val'),
  layerEdgeFade: document.getElementById('layer-edge-fade'),
  layerEdgeFadeVal: document.getElementById('layer-edge-fade-val'),
  luminositySmoothnessGroup: document.getElementById('luminosity-smoothness-group'),
  hueTolerance: document.getElementById('hue-tolerance'),
  hueToleranceVal: document.getElementById('hue-tolerance-val'),
  colorRangeHueGroup: document.getElementById('color-range-hue-group'),
  btnRegenerateLayers: document.getElementById('btn-regenerate-layers'),
  btnRandomLayersOrder: document.getElementById('btn-random-layers-order'),
  layersList: document.getElementById('layers-list'),

  // Inspector UI elements
  layerInspectorSection: document.getElementById('layer-inspector-section'),
  inspectorPreviewCanvas: document.getElementById('inspector-preview-canvas'),
  inspectorLayerName: document.getElementById('inspector-layer-name'),
  inspectorLayerStat: document.getElementById('inspector-layer-stat'),
  inspectorBgSelectors: document.querySelectorAll('.inspector-bg-selectors .bg-btn'),

  mainCanvas: document.getElementById('main-canvas'),
  canvasLoading: document.getElementById('canvas-loading'),
  glitchFlash: document.getElementById('glitch-flash'),
  fpsValue: document.getElementById('fps-value'),
  themeSelect: document.getElementById('theme-select'),

  btnPlayPause: document.getElementById('btn-play-pause'),
  playPauseIcon: document.getElementById('play-pause-icon'),
  btnStep: document.getElementById('btn-step'),
  btnManualGlitch: document.getElementById('btn-manual-glitch'),
  btnToggleGrid: document.getElementById('btn-toggle-grid'),
  btnResetView: document.getElementById('btn-reset-view'),
  btnFullscreen: document.getElementById('btn-fullscreen'),

  // Toggles
  glitchEnabled: document.getElementById('glitch-enabled'),
  aspectRatio: document.getElementById('aspect-ratio'),

  zoomSpeed: document.getElementById('zoom-speed'),
  zoomSpeedVal: document.getElementById('zoom-speed-val'),
  zoomDepth: document.getElementById('zoom-depth'),
  zoomDepthVal: document.getElementById('zoom-depth-val'),
  cameraRotation: document.getElementById('camera-rotation'),
  cameraRotationVal: document.getElementById('camera-rotation-val'),
  cameraDrift: document.getElementById('camera-drift'),
  cameraDriftVal: document.getElementById('camera-drift-val'),

  mirrorMode: document.getElementById('mirror-mode'),
  kSlices: document.getElementById('k-slices'),
  kSlicesVal: document.getElementById('k-slices-val'),
  kaleidoscopeSlicesGroup: document.getElementById('kaleidoscope-slices-group'),

  rgbSplit: document.getElementById('rgb-split'),
  rgbSplitVal: document.getElementById('rgb-split-val'),
  pixelSort: document.getElementById('pixel-sort'),
  pixelSortVal: document.getElementById('pixel-sort-val'),
  glitchFrequency: document.getElementById('glitch-frequency'),
  glitchFrequencyVal: document.getElementById('glitch-frequency-val'),
  glitchSeverity: document.getElementById('glitch-severity'),
  glitchSeverityVal: document.getElementById('glitch-severity-val'),
  depthModulation: document.getElementById('depth-modulation'),
  depthModulationVal: document.getElementById('depth-modulation-val'),

  exportMode: document.getElementById('export-mode'),
  exportDuration: document.getElementById('export-duration'),
  exportDurationVal: document.getElementById('export-duration-val'),
  exportDurationGroup: document.getElementById('export-duration-group'),
  exportLoops: document.getElementById('export-loops'),
  exportLoopsVal: document.getElementById('export-loops-val'),
  exportLoopsGroup: document.getElementById('export-loops-group'),
  exportEstimateText: document.getElementById('export-estimate-text'),
  exportFps: document.getElementById('export-fps'),
  exportResolution: document.getElementById('export-resolution'),
  btnExportVideo: document.getElementById('btn-export-video'),
  exportOverlay: document.getElementById('export-overlay'),
  exportProgressBar: document.getElementById('export-progress-bar'),
  exportFrameCount: document.getElementById('export-frame-count'),
  exportPercent: document.getElementById('export-percent'),
  btnCancelExport: document.getElementById('btn-cancel-export'),
  videoFadeActive: document.getElementById('video-fade-active'),
  videoFadeDivider: document.getElementById('video-fade-divider'),
  videoFadeDurationGroup: document.getElementById('video-fade-duration-group'),
  videoFadeDuration: document.getElementById('video-fade-duration'),
  videoFadeDurationVal: document.getElementById('video-fade-duration-val'),

  // Text Settings Section References
  textSettingsSection: document.getElementById('text-settings-section'),
  textContent: document.getElementById('text-content'),
  textFont: document.getElementById('text-font'),
  btnLoadFont: document.getElementById('btn-load-font'),
  fontFileInput: document.getElementById('font-file-input'),
  textSize: document.getElementById('text-size'),
  textSizeVal: document.getElementById('text-size-val'),
  textColor: document.getElementById('text-color'),
  textPosX: document.getElementById('text-pos-x'),
  textPosXVal: document.getElementById('text-pos-x-val'),
  textPosY: document.getElementById('text-pos-y'),
  textPosYVal: document.getElementById('text-pos-y-val'),
  textAngle: document.getElementById('text-angle'),
  textAngleVal: document.getElementById('text-angle-val'),
  textIdleWobble: document.getElementById('text-idle-wobble'),
  textIdleWobbleVal: document.getElementById('text-idle-wobble-val'),
  textIdleSkew: document.getElementById('text-idle-skew'),
  textIdleSkewVal: document.getElementById('text-idle-skew-val'),
  textGlitchMode: document.getElementById('text-glitch-mode'),
  textGlitchIntensity: document.getElementById('text-glitch-intensity'),
  textGlitchIntensityVal: document.getElementById('text-glitch-intensity-val'),
  textGlitchMono: document.getElementById('text-glitch-mono'),
  textTransition: document.getElementById('text-transition'),
  textTransitionDuration: document.getElementById('text-transition-duration'),
  textTransitionDurationVal: document.getElementById('text-transition-duration-val'),
  btnCopyText: document.getElementById('btn-copy-text'),
  btnDeleteText: document.getElementById('btn-delete-text'),

  // Audio Settings Section References
  audioSettingsSection: document.getElementById('audio-settings-section'),
  audioFileName: document.getElementById('audio-file-name'),
  audioFileDuration: document.getElementById('audio-file-duration'),
  audioTimelineStart: document.getElementById('audio-timeline-start'),
  audioTimelineStartVal: document.getElementById('audio-timeline-start-val'),
  audioVolume: document.getElementById('audio-volume'),
  audioVolumeVal: document.getElementById('audio-volume-val'),
  btnDeleteAudio: document.getElementById('btn-delete-audio'),

  // Graphic Settings Section References
  graphicSettingsSection: document.getElementById('graphic-settings-section'),
  graphicFileName: document.getElementById('graphic-file-name'),
  graphicTimelineStart: document.getElementById('graphic-timeline-start'),
  graphicTimelineStartVal: document.getElementById('graphic-timeline-start-val'),
  graphicTimelineEnd: document.getElementById('graphic-timeline-end'),
  graphicTimelineEndVal: document.getElementById('graphic-timeline-end-val'),
  graphicPosX: document.getElementById('graphic-pos-x'),
  graphicPosXVal: document.getElementById('graphic-pos-x-val'),
  graphicPosY: document.getElementById('graphic-pos-y'),
  graphicPosYVal: document.getElementById('graphic-pos-y-val'),
  graphicScale: document.getElementById('graphic-scale'),
  graphicScaleVal: document.getElementById('graphic-scale-val'),
  graphicGlitchFrequency: document.getElementById('graphic-glitch-frequency'),
  graphicGlitchFrequencyVal: document.getElementById('graphic-glitch-frequency-val'),
  graphicGlitchAmplitude: document.getElementById('graphic-glitch-amplitude'),
  graphicGlitchAmplitudeVal: document.getElementById('graphic-glitch-amplitude-val'),
  graphicFlickerIntensity: document.getElementById('graphic-flicker-intensity'),
  graphicFlickerIntensityVal: document.getElementById('graphic-flicker-intensity-val'),
  btnDeleteGraphic: document.getElementById('btn-delete-graphic'),

  // Timeline Panel References
  btnAddTextNew: document.getElementById('btn-add-text-new'),
  btnAddTextSame: document.getElementById('btn-add-text-same'),
  btnAddGraphic: document.getElementById('btn-add-graphic'),
  graphicFileInput: document.getElementById('graphic-file-input'),
  btnAddAudio: document.getElementById('btn-add-audio'),
  audioFileInput: document.getElementById('audio-file-input'),
  timelineTimecode: document.getElementById('timeline-timecode'),
  btnTimelineStart: document.getElementById('btn-timeline-start'),
  btnTimelineEnd: document.getElementById('btn-timeline-end'),
  timelineDurationControl: document.getElementById('timeline-duration-control'),
  timelineDurationSlider: document.getElementById('timeline-duration-slider'),
  timelineDurationVal: document.getElementById('timeline-duration-val'),
  timelineRuler: document.getElementById('timeline-ruler'),
  timelineTracks: document.getElementById('timeline-tracks'),
  timelinePlayhead: document.getElementById('timeline-playhead'),
  timelineTracksContainer: document.getElementById('timeline-tracks-container'),
  btnResetRotation: document.getElementById('btn-reset-rotation')
};
